### ISSUE TITLE
How to set the color of the font on the image.

### ISSUE THREAD

**Issue by paulzhang5511** [daniel-e/captcha#1]
![image](https://user-images.githubusercontent.com/53463972/65420298-5d358e00-de33-11e9-8bcf-74dfd8e55a7f.png)

How to set the color of the font on the image.

**Comment by daniel-e** [comment]
At the moment this is not possible. It should not be a big issue and I will consider it for the future.

**Comment by starccy** [comment]
@daniel-e Would it will be better if we draw letters directly on images instead of putting letter pngs on them? There are already some functions in image crate to do it. Then we could have more flexibility in text operation such as change text color or use more fonts.

**Comment by daniel-e** [comment]
Just added the function set_color() where you can specify the RGB values of the color.
