### ISSUE TITLE
Works as designed, but...

### ISSUE THREAD

**Issue by 4parsleythelion** [daniel-e/captcha#2]
Hi Sir,

I use your Captcha crate in Rocket, and I producing images, great. Now as I'm a novice at Rust I can't work out how to get the string that the image is displaying so I can compare it. Sorry to ask such a stupid question but I'm a little stuck.

The crate is working great and the documents got me this far.

Thank you for your time and effort,

Ashley

**Comment by PeterUlb** [comment]
https://docs.rs/captcha/0.0.7/captcha/struct.Captcha.html#method.chars

Just call it on your captcha instance.

**Comment by 4parsleythelion** [comment]
Peter,

Thank you for the reply, and I used the following, which works like a champ:

let mut cap = Captcha::new();
cap.add_chars(5);
cap.apply_filter(Noise::new(0.2));
cap.apply_filter(Wave::new(2.0, 20.0));
cap.view(220, 120);
cap.save(Path::new("./static/captcha.png")).expect("save failed");
let capkey = Captcha::chars_as_string(&cap);

Thank you once again.

Ashley

**Comment by daniel-e** [comment]
Just added an example to the example files.
